name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Build Docker image
        run: |
          docker build -t my-app-backend .
        
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-app-backend ${{ secrets.DOCKER_USERNAME }}/my-app-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app-backend:latest

      - name: Deploy to K3s
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/nestjs-deployment.yaml
